### ISSUE TITLE
channels.nim might not be thread safe

### ISSUE THREAD

**Issue by zevv** [nim-lang/threading#24]
I believe there are a number of problems with the channels.nim implementation with regards to unprotected access to the queue's head and tail pointers, as the `hLock` and `tLock` mutexes do not seem to consistently lock the respective `head` and `tail` indices. 

For example: `sendMpmc()` calls `chan.isFull()` while holding only the `hLock`, but `chan.isFull()` also accesses the `tail` pointer.

Running `tests/tchannels_simple` under valgrind/helgrind or the gcc/clang thread sanitizers will point out a number of similar errors throughout the code.

**Comment by ZoomRmc** [comment]
Yep. This is what I meant when I said my latest PR *partly* fixes #19.
From what I gathered, this unprotected access to both pointers happened in the original code (channels_legacy.nim) this implementation was based on. I'm sorry I didn't have time yet to fix it. Although I didn't expect my messing with the code may really improve its measurable qualities, my intention was not to make it worse, and that's exactly what happened with reintroducing two locks.

**Comment by zevv** [comment]
Right, that makes sense, thanks for confirming.

Given that this library is now an essential piece of Nim infrastructure that is referred to by the Nim core team when someone asks how to do proper threading in Nim 2.0, I feel it could benefit from being looked at with some more scrutiny.

I do not know what the previous implementation looked like, but I do not see the benefit of using separate locks for head and tail indices; whenever you need to check if the queue is either full or empty, you need to be able to check both head and tail pointers, so either one needs to be protected by a lock; this would make your regular operations even more expensive as you now have to take *two* locks when either adding or removing from the queue. Tripping up on ordering with two locks is also guaranteed to result in deadlocks.

As I mentioned in my original post: running the tests under Helgrind or tsan will result in a detailed log of all the places where thread safety is violated; I would recommend taking the results of these tools very serious and making this an essential part of the CI test. Also, the new `{.guard:XXX.}` annotation can help ensure the code is at least holding the appropriate locks when touching critical data.

**Comment by ZoomRmc** [comment]
I agree, having two locks makes sense if you're about to be concurrently accessing head and tail of the buffer and it's the *only* thing that's changing. In principle this works for an unbounded buffer, where things are added/removed from at leisure. But when both operations affect the state of the whole structure (the current length of a bounded buffer which needs to be checked for both ops), all assumptions fail unless the whole state changes in a coordinated way.

**Comment by Lancer11211** [comment]
SharedPtr isn't thread safe either. I recently started to wrap two channels into objects and shared ptrs to have inter-thread communication between a number of threads but I'm getting sigsegv all the time.

**Comment by mratsim** [comment]
> I believe there are a number of problems with the channels.nim implementation with regards to unprotected access to the queue's head and tail pointers, as the hLock and tLock mutexes do not seem to consistently lock the respective head and tail indices.

> I do not know what the previous implementation looked like, but I do not see the benefit of using separate locks for head and tail indices; whenever you need to check if the queue is either full or empty, you need to be able to check both head and tail pointers, so either one needs to be protected by a lock; this would make your regular operations even more expensive as you now have to take two locks when either adding or removing from the queue. Tripping up on ordering with two locks is also guaranteed to result in deadlocks.

The goal of having two locks is having producers only compete with themselves for locking and consumers only compete with themselves for locking. This significantly reduce overhead compared to a single lock and is a design that has been heavily tested since its publication in 1996, see the blocking queue paper: https://www.cs.rochester.edu/~scott/papers/1996_PODC_queues.pdf

Regarding isFull vs isEmpty, whetever multithreaded queue design you use, they are always approximative because if multiple threads compete in enqueueing and dequeuing items 1 nanosecond after you query your count will be wrong whether you locked the queue or not. So any multithreaded queue user needs to deal with that, usually by polling or establishing another signaling mechanism.

Note: I didn't review the implementation.

**Comment by ZoomRmc** [comment]
Currently it's two locks and will probably stay this way unless the whole implementation changes to be based on some other thing, such as McKenney-Howells [ringubffer](https://github.com/torvalds/linux/blob/master/Documentation/core-api/circular-buffers.rst)

> Regarding isFull vs isEmpty, whatever multithreaded queue design you use, they are always approximative because if multiple threads compete in enqueueing and dequeuing items 1 nanosecond after you query your count will be wrong whether you locked the queue or not.

I think this is one of the reasons having a sentinel value is a good idea. Also, the two-lock buffer in the PODC is unbounded (linked-list based) and non-blocking (bails out). I'm not sure the ad-hoc changing it to the bounded version, making sure it never overlaps and supporting both blocking and non-blocking operation is as comparably sound and well-tested as the original. Honestly, the current implementation doesn't have much common with the PODC fig.2 besides using two-locks.

**Comment by zevv** [comment]
I just saw that commit 9c74c61655356ecf9731c42adf84282752ae2082 reverted the code that caused this issue, so closing this for now.

**Comment by ZoomRmc** [comment]
> I just saw that commit [9c74c61](https://github.com/nim-lang/threading/commit/9c74c61655356ecf9731c42adf84282752ae2082) reverted the code that caused this issue, so closing this for now.

Technically they still might, so I didn't mark it as resolved :D
