### ISSUE TITLE
Deprecate or remove atomics?

### ISSUE THREAD

**Issue by planetis-m** [nim-lang/threading#35]
It seems that this module have fallen out of grace, with the respective RFC closed. Is it supposed to be deprecated in favor of std/atomics?

**Comment by Araq** [comment]
I think so, yes.

**Comment by konsumlamm** [comment]
`std/atomics` and `threading/atomics` look very similar, but there are some differences:
* `std` has an annoying `mo` prefix for memory orderings
* `std` also supports non-trivial types, which is a bit of a footgun (see also https://github.com/nim-lang/RFCs/issues/445), although `AtomType` is a bit restrictive

So I like the `threading` version a bit better. If `std/atomics` should be preferred, it should at least be made stable.
