### ISSUE TITLE
Is trySend failing to send a message without returning false?

### ISSUE THREAD

**Issue by PhilippMDoerner** [nim-lang/threading#52]
Wanting to play around with the differences between system.Channel and threading Chan I wrote myself a small micro benchmark to poke at both and see how they perform.

While doing so I noticed that a decent chunk of messages when rapidly sending them through the channel get lost, but without trySend returning false (?). This was tested by sending a message to another thread via channel3, which immediately returns the message through channel4.

Here a small-ish example of the micro-benchmark cut down to show only the problem:
```nim
import std/[os, sequtils]
import threading/channels

const MESSAGE_COUNT = 100

type LargeMessage = object
  lotsOfNumbers: seq[int]
type MsgType = LargeMessage

type Container = object
  chan1: Channel[MsgType]
  chan2: Channel[MsgType]
  chan3: Chan[MsgType]
  chan4: Chan[MsgType]

proc setupChanReceiver(cont: var Container): Thread[ptr Container] =
  proc recvMsg(container: ptr Container) =
    var serverCounter = 0
    while true:
      var msg: MsgType
      let dataAvailable = container[].chan3.tryRecv(msg)
      if dataAvailable:
        serverCounter.inc
        discard container[].chan4.trySend(msg)
    
  createThread(result, recvMsg, cont.addr)

proc main() =
  var chan1: Channel[MsgType]
  var chan2: Channel[MsgType]
  chan1.open()
  chan2.open()
  var cont = Container(chan1: chan1, chan2: chan2, chan3: newChan[MsgType](), chan4: newChan[MsgType]())
  let msg: MsgType = LargeMessage(lotsOfNumbers: (1..1000).toSeq()) #"Test"
  var sendCounter = 0
  var failedCounter = 0

  # Test2
  let chanReceiverThread = setupChanReceiver(cont)
  sendCounter = 0
  failedCounter = 0
  var counter = 0
  for _ in 0..(MESSAGE_COUNT*2):
    sendCounter.inc
    let success = cont.chan3.trySend(msg)
    if not success:
      failedCounter.inc
  echo "Sent Message count: ", sendCounter, " - Of which failed: ", failedCounter

  while counter < MESSAGE_COUNT:
    var msg: MsgType
    let dataAvailable = cont.chan4.tryRecv(msg)
    if dataAvailable:
      echo "in channels: chan3: ", cont.chan3.peek(), " - chan4: ", cont.chan4.peek()
      counter.inc
    
  # echo "Sent Message count: ", sendCounter, " - Of which failed: ", failedCounter
  joinThreads(chanReceiverThread)
  
main()
```
It delivers the following output:
```txt
Sent Message count: 201 - Of which failed: 0
in channels: chan3: 0 - chan4: 29
in channels: chan3: 0 - chan4: 28
in channels: chan3: 0 - chan4: 27
in channels: chan3: 0 - chan4: 26
... You can imagine the rest ...
in channels: chan3: 0 - chan4: 3
in channels: chan3: 0 - chan4: 2
in channels: chan3: 0 - chan4: 1
in channels: chan3: 0 - chan4: 0
```

So multiple questions related to this:

1) I pump 201 messages into channel 3 and somehow I only get 30 replies? Why am I not getting back at least 100 (which should break the while-loop on the client side) ?
2) Why does trySend not return false (as seen bei failedCounter being 0) when it appears that the server only received 30 messages?

**Comment by Araq** [comment]
Is `send` also affected or only `trySend`?

**Comment by PhilippMDoerner** [comment]
It seems so. I mean, not that I understand any of this, but my gut feeling makes this seem as if the queue gets "clogged" somehow when the number of messages in chan4 (the channel that the "chanReceiver" thread uses to send messages to the main-thread - chan3 is for sending messages to the "chanReceiver" channel) reaches 30 and it tries to send the 31st message.

I modified the example above to demonstrate this:
```nim
import std/[os, sequtils]
import threading/channels

const MESSAGE_COUNT = 100

type LargeMessage = object
  lotsOfNumbers: seq[int]
type MsgType = LargeMessage

type Container = object
  chan1: Channel[MsgType]
  chan2: Channel[MsgType]
  chan3: Chan[MsgType]
  chan4: Chan[MsgType]

proc setupChanReceiver(cont: var Container): Thread[ptr Container] =
  proc recvMsg(container: ptr Container) =
    var serverCounter = 0
    while true:
      var msg: MsgType
      let dataAvailable = container[].chan3.tryRecv(msg)
      if dataAvailable:
        serverCounter.inc
        echo "Beforesend"
        container[].chan4.send(msg)
        echo "Sent message, msg in chan3: ", container[].chan3.peek(), " msg in chan4: ", container[].chan4.peek()
    
  createThread(result, recvMsg, cont.addr)

proc main() =
  var chan1: Channel[MsgType]
  var chan2: Channel[MsgType]
  chan1.open()
  chan2.open()
  var cont = Container(chan1: chan1, chan2: chan2, chan3: newChan[MsgType](), chan4: newChan[MsgType]())
  let msg: MsgType = LargeMessage(lotsOfNumbers: (1..1000).toSeq()) #"Test"
  var sendCounter = 0
  var failedCounter = 0

  # Test2
  let chanReceiverThread = setupChanReceiver(cont)
  sendCounter = 0
  failedCounter = 0
  var counter = 0
  for _ in 0..(MESSAGE_COUNT*2):
    sendCounter.inc
    cont.chan3.send(msg)

  echo "Sent Message count: ", sendCounter

  while counter < MESSAGE_COUNT:
    var msg: MsgType
    let dataAvailable = cont.chan4.tryRecv(msg)
    if dataAvailable:
      echo "Msg Count received: ", counter, " - Msg in channels: chan3: ", cont.chan3.peek(), " - chan4: ", cont.chan4.peek()
      counter.inc
    
  # echo "Sent Message count: ", sendCounter, " - Of which failed: ", failedCounter
  joinThreads(chanReceiverThread)
  
main()
```

Look at `setupChanReceiver`, with the echo's before and after the send call. If send is always successful, the messages in the terminal should never end with a "Beforesend". However, that is what we're seeing:

Running this, we get:
```txt
Beforesend
Sent message, msg in chan3: 25 msg in chan4: 1
Beforesend
Sent message, msg in chan3: 29 msg in chan4: 2
Beforesend
Sent message, msg in chan3: 30 msg in chan4: 3
... You can imagine the rest ...
Sent message, msg in chan3: 30 msg in chan4: 29
Beforesend
Sent message, msg in chan3: 30 msg in chan4: 30
Beforesend
```

It ends in Beforesend, so the chanReceiver thread gets stuck on `container[].chan4.send(msg)`

**Comment by PhilippMDoerner** [comment]
I've since had a chat with Elegantbeef and learned a decent chunk more.

Apparently threading/channels.Chan are fixed-size queues whose capacity you define when instantiating them (That's what the elements parameter is for, I did **not** understand that).

So the queues being fixed size and me **first** sending out 200 messages from Thread A is the problem.
Thread B is super fast and immediately sends replies, which clog up the channel that Thread A reads from because Thread A has not yet reached its while-loop where it starts reading from there.

That's why it gets stuck (or drops a bunch of messages when using trySend) - the queue to Thread A is already full before Thread A starts reading from it and Thread B tries to push more messages into it.

The question that Beef wanted me to add here was: This means that the Channels can't grow. Is that intentional or should there be an "auto-grow" ability (which apparently system.Channel has(?), didn't have the problem with it).

**Comment by Araq** [comment]
It is intended and also acts as a "throttling" mechanism. The sender blocks until space is ready again. This is usually not a problem if you start the sending and receiving threads properly at roughly the same time.

It's a general problem in concurrent systems and an auto-grow feature only invites designs that use way more memory than required. IMHO the whole approach with channels is a kludge and the real thing that everybody really wants is the `spawn` primitive.

**Comment by PhilippMDoerner** [comment]
Alrighty, that means documentation time. I'll see what I can kudgel together when I have more brainspace.
Documentation at least is the one thing where I'd be confident enough to make submissions for.
